// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type CreateGenreInput struct {
	Name string `json:"name"`
}

type CreateSongInput struct {
	Title  string `json:"title"`
	Artist string `json:"artist"`
}

type CreateUserInput struct {
	Email          string   `json:"email"`
	UserName       string   `json:"userName"`
	FavoriteGenres []string `json:"favoriteGenres"`
}

type GenreListDto struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Mutation struct {
}

type Query struct {
}

type SongListDto struct {
	ID     uuid.UUID `json:"id"`
	Title  string    `json:"title"`
	Artist string    `json:"artist"`
}

type UserListDto struct {
	ID       uuid.UUID `json:"id"`
	UserName string    `json:"userName"`
	Email    string    `json:"email"`
}
